<?php
// Generated by generator/generate-registry.php -- DO NOT EDIT

declare(strict_types=1);

namespace Klkvsk\Whoeasy\Registry\Data;

/**
 * IPv6 ranges: [prefixLong, maskLong, whoisServer, rdapUrl].
 */
final class Ipv6Ranges
{
    /** @return array<int, array{0: int, 1: int, 2: string, 3: ?string}> */
    public static function data(): array
    {
        return [
    [536936960, 4294966784, 'whois.apnic.net', 'https://rdap.apnic.net/'],
    [536937472, 4294966784, 'whois.arin.net', 'https://rdap.arin.net/registry/'],
    [536937984, 4294966784, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536938496, 4294966272, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536939520, 4294966272, 'whois.apnic.net', 'https://rdap.apnic.net/'],
    [536940544, 4294966272, 'whois.lacnic.net', 'https://rdap.lacnic.net/rdap/'],
    [536941568, 4294966272, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536942592, 4294966784, 'whois.arin.net', 'https://rdap.arin.net/registry/'],
    [536943104, 4294966784, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536943616, 4294966272, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536944640, 4294959104, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536952832, 4294966784, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536953344, 4294966784, 'whois.afrinic.net', 'https://rdap.afrinic.net/rdap/'],
    [536953856, 4294966784, 'whois.apnic.net', 'https://rdap.apnic.net/'],
    [536954368, 4294966784, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536954880, 4294966784, 'whois.arin.net', 'https://rdap.arin.net/registry/'],
    [536955392, 4294966784, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536955904, 4294966272, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536956928, 4294963200, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [536969216, 4294950912, 'whois.apnic.net', 'https://rdap.apnic.net/'],
    [537067520, 4294950912, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [603979776, 4294963200, 'whois.nic.or.kr', null],
    [603979776, 4292870144, 'whois.apnic.net', 'https://rdap.apnic.net/'],
    [637534208, 4293918720, 'whois.arin.net', 'https://rdap.arin.net/registry/'],
    [638582784, 4294966784, 'whois.arin.net', 'https://rdap.arin.net/registry/'],
    [639631360, 4294966784, 'whois.arin.net', 'https://rdap.arin.net/registry/'],
    [640679936, 4293918720, 'whois.arin.net', 'https://rdap.arin.net/registry/'],
    [671088640, 4293918720, 'whois.lacnic.net', 'https://rdap.lacnic.net/rdap/'],
    [704643072, 4292870144, 'whois.ripe.net', 'https://rdap.db.ripe.net/'],
    [738197504, 4293918720, 'whois.afrinic.net', 'https://rdap.afrinic.net/rdap/'],
        ];
    }
}
